cli:
    build: ../cli
    links:
        - redis:redis.dev.caliopen.org
        - cassandra:cassandra.dev.caliopen.org
        - elasticsearch:es.dev.caliopen.org
    volumes:
      - ../poc_fixtures/fixtures:/usr/share/caliopen/poc_fixtures
    command: ['caliopen']
